### PR TITLE
54 Added vote removal, getters for voted and delegated implemented an…

### PR DESCRIPTION
**Pull request by aecc**
…d visible in the GUI

Fixes for (3) and (4) including connection to GUI in #54 

@medied @AlexJupiter @LucasIsasmendi 
I propose here that we define better the terminology of "revoking" to avoid further language issues. In this code I included:

- Remove vote: to remove a vote from YES/NO
- Revoke: to revoke a delegation to another Voter

Let me know if you agree

Screenshots:

**Remove vote:**
image

**Revoke:**
image

### CODE REVIEW

**Comment by LucasIsasmendi** [comment]
We should try to be as close as possible with sovereign meteor app. The UX presents the following options: cast votes, revoked votes, granted votes, remove delegation, remove votes

**Comment by aecc** [comment]
Agree. So it seems that we can conclude that we can use the revoke word only in past, as in "revoked". Remove vote, remove delegation, revoked vote, revoked delegation.
Do we all agree?

**Comment by AlexJupiter** [comment]
@aecc this reasoning sounds good to me!

**Comment by aecc** [comment]
Ok, I'll change the naming and push the changes.

**Comment by aecc** [comment]
Terminology changed as discussed. Merging..

**Pull request merged**
